package handlers

import (
	controllers "easy-wallet-be/src/controllers/auth"
	schemas "easy-wallet-be/src/data/schemas/auth/resetPassword"
	"easy-wallet-be/src/utils"
	"net/http"

	"github.com/labstack/echo/v4"
)

// ResetPassword is a handler function that resets the user's password.
// It receives a token and a new password in the request body.
// It verifies if the token is valid and was generated by the GenerateToken function.
// It hashes the new password and changes the user's password to the new password.
// It returns a success message if the password was reset successfully.
func ResetPassword(c echo.Context) error {
	token := c.Param("token")

	var bodyData schemas.BodyData
	c.Bind(&bodyData)

	// Verify if the token was generated by the GenerateToken function
	if !utils.ValidateToken(token) {
		return utils.HandleResponse(
			c,
			http.StatusBadRequest,
			"Invalid token",
			nil,
		)
	}

	// Hash password
	hashedPassword, err := utils.HashPassword(bodyData.NewPassword)
	if err != nil {
		return utils.HandleResponse(
			c,
			http.StatusInternalServerError,
			"An error occurred while trying to update your password",
			nil,
		)
	}

	// Change the user's password to the new password
	if err := controllers.ResetPassword(token, hashedPassword); err != nil {
		return utils.HandleResponse(
			c,
			http.StatusNotFound,
			"User not found",
			nil,
		)
	}

	return utils.HandleResponse(
		c,
		http.StatusOK,
		"Password reset successfully",
		nil,
	)
}
